spring:
  datasource:
    url: jdbc:mysql://localhost:3306/viajes
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: validate
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
